Author.create!([
  {first: "Afton", last: "Terry", age: 89},
  {first: "Dalton", last: "Gerlach", age: 22},
  {first: "Gaylord", last: "Hansen", age: 23},
  {first: "Claudine", last: "Upton", age: 44},
  {first: "Marques", last: "DuBuque", age: 58},
  {first: "Josue", last: "Crist", age: 6},
  {first: "Triston", last: "Feil", age: 61},
  {first: "Megane", last: "Hodkiewicz", age: 50},
  {first: "Luther", last: "Nader", age: 53},
  {first: "Abner", last: "Padberg", age: 30},
  {first: "Caitlyn", last: "Armstrong", age: 55},
  {first: "Daryl", last: "Vandervort", age: 15},
  {first: "Philip", last: "Deckow", age: 8},
  {first: "Lora", last: "Dietrich", age: 98},
  {first: "Hortense", last: "O'Conner", age: 82},
  {first: "Gracie", last: "Franecki", age: 13},
  {first: "Kathlyn", last: "Fadel", age: 59},
  {first: "Adrien", last: "Satterfield", age: 52},
  {first: "Vladimir", last: "Rohan", age: 67},
  {first: "Paul", last: "Dibbert", age: 56},
  {first: "Taurean", last: "Rohan", age: 93},
  {first: "Nya", last: "Stamm", age: 44},
  {first: "Myron", last: "Miller", age: 81},
  {first: "Lazaro", last: "Corkery", age: 22},
  {first: "Palma", last: "Frami", age: 75},
  {first: "Reid", last: "Donnelly", age: 28},
  {first: "Kaia", last: "Ward", age: 37},
  {first: "Brendon", last: "Jacobs", age: 5},
  {first: "Zoila", last: "Vandervort", age: 47},
  {first: "Brendan", last: "Parker", age: 63},
  {first: "Ubaldo", last: "Gutmann", age: 49},
  {first: "Viva", last: "Mitchell", age: 95},
  {first: "Stephany", last: "Kling", age: 65},
  {first: "Braeden", last: "Kreiger", age: 20},
  {first: "Krystal", last: "Hettinger", age: 40},
  {first: "Russell", last: "Waters", age: 24},
  {first: "Ibrahim", last: "Wisozk", age: 78},
  {first: "Gerard", last: "MacGyver", age: 79},
  {first: "Charity", last: "Glover", age: 30},
  {first: "Precious", last: "Prosacco", age: 78},
  {first: "German", last: "Gusikowski", age: 18},
  {first: "Shanie", last: "Ortiz", age: 75},
  {first: "Kay", last: "Ryan", age: 38},
  {first: "Carleton", last: "McClure", age: 40},
  {first: "Addie", last: "Brekke", age: 19},
  {first: "Billie", last: "Labadie", age: 86},
  {first: "Tod", last: "Lemke", age: 40},
  {first: "Ivy", last: "Konopelski", age: 23},
  {first: "Enos", last: "Corkery", age: 49},
  {first: "Nella", last: "Hermann", age: 41}
])
Book.create!([
  {pages: 3, copywright: 33, author_id: 1},
  {pages: 0, copywright: 589, author_id: 1},
  {pages: 7, copywright: 196, author_id: 2},
  {pages: 7, copywright: 1736, author_id: 2},
  {pages: 1, copywright: 389, author_id: 3},
  {pages: 6, copywright: 1164, author_id: 3},
  {pages: 4, copywright: 546, author_id: 4},
  {pages: 3, copywright: 996, author_id: 4},
  {pages: 3, copywright: 1515, author_id: 5},
  {pages: 4, copywright: 175, author_id: 5},
  {pages: 1, copywright: 835, author_id: 6},
  {pages: 3, copywright: 538, author_id: 6},
  {pages: 9, copywright: 1084, author_id: 7},
  {pages: 4, copywright: 1144, author_id: 7},
  {pages: 0, copywright: 805, author_id: 8},
  {pages: 2, copywright: 566, author_id: 8},
  {pages: 5, copywright: 153, author_id: 9},
  {pages: 7, copywright: 179, author_id: 9},
  {pages: 7, copywright: 1645, author_id: 10},
  {pages: 7, copywright: 1063, author_id: 10},
  {pages: 8, copywright: 968, author_id: 11},
  {pages: 5, copywright: 49, author_id: 11},
  {pages: 8, copywright: 1609, author_id: 12},
  {pages: 2, copywright: 55, author_id: 12},
  {pages: 0, copywright: 660, author_id: 13},
  {pages: 0, copywright: 92, author_id: 13},
  {pages: 4, copywright: 936, author_id: 14},
  {pages: 5, copywright: 411, author_id: 14},
  {pages: 6, copywright: 332, author_id: 15},
  {pages: 0, copywright: 615, author_id: 15},
  {pages: 8, copywright: 577, author_id: 16},
  {pages: 9, copywright: 565, author_id: 16},
  {pages: 3, copywright: 588, author_id: 17},
  {pages: 4, copywright: 656, author_id: 17},
  {pages: 8, copywright: 820, author_id: 18},
  {pages: 5, copywright: 1052, author_id: 18},
  {pages: 1, copywright: 975, author_id: 19},
  {pages: 1, copywright: 1191, author_id: 19},
  {pages: 7, copywright: 420, author_id: 20},
  {pages: 2, copywright: 1747, author_id: 20},
  {pages: 6, copywright: 1547, author_id: 21},
  {pages: 0, copywright: 741, author_id: 21},
  {pages: 4, copywright: 1557, author_id: 22},
  {pages: 5, copywright: 13, author_id: 22},
  {pages: 3, copywright: 1379, author_id: 23},
  {pages: 6, copywright: 377, author_id: 23},
  {pages: 7, copywright: 1004, author_id: 24},
  {pages: 1, copywright: 1333, author_id: 24},
  {pages: 1, copywright: 764, author_id: 25},
  {pages: 9, copywright: 26, author_id: 25},
  {pages: 4, copywright: 1407, author_id: 26},
  {pages: 3, copywright: 1429, author_id: 26},
  {pages: 4, copywright: 1007, author_id: 27},
  {pages: 1, copywright: 227, author_id: 27},
  {pages: 9, copywright: 513, author_id: 28},
  {pages: 2, copywright: 51, author_id: 28},
  {pages: 7, copywright: 1112, author_id: 29},
  {pages: 6, copywright: 461, author_id: 29},
  {pages: 5, copywright: 1393, author_id: 30},
  {pages: 3, copywright: 1484, author_id: 30},
  {pages: 3, copywright: 1779, author_id: 31},
  {pages: 7, copywright: 480, author_id: 31},
  {pages: 2, copywright: 594, author_id: 32},
  {pages: 3, copywright: 243, author_id: 32},
  {pages: 1, copywright: 1204, author_id: 33},
  {pages: 7, copywright: 1362, author_id: 33},
  {pages: 9, copywright: 869, author_id: 34},
  {pages: 4, copywright: 1299, author_id: 34},
  {pages: 7, copywright: 1535, author_id: 35},
  {pages: 5, copywright: 1392, author_id: 35},
  {pages: 7, copywright: 1662, author_id: 36},
  {pages: 0, copywright: 1153, author_id: 36},
  {pages: 7, copywright: 572, author_id: 37},
  {pages: 3, copywright: 1384, author_id: 37},
  {pages: 0, copywright: 1384, author_id: 38},
  {pages: 1, copywright: 6, author_id: 38},
  {pages: 7, copywright: 1188, author_id: 39},
  {pages: 3, copywright: 36, author_id: 39},
  {pages: 0, copywright: 1580, author_id: 40},
  {pages: 5, copywright: 1698, author_id: 40},
  {pages: 3, copywright: 1456, author_id: 41},
  {pages: 9, copywright: 343, author_id: 41},
  {pages: 9, copywright: 1774, author_id: 42},
  {pages: 2, copywright: 814, author_id: 42},
  {pages: 5, copywright: 1013, author_id: 43},
  {pages: 0, copywright: 1413, author_id: 43},
  {pages: 0, copywright: 1579, author_id: 44},
  {pages: 6, copywright: 1308, author_id: 44},
  {pages: 8, copywright: 609, author_id: 45},
  {pages: 0, copywright: 1347, author_id: 45},
  {pages: 2, copywright: 203, author_id: 46},
  {pages: 4, copywright: 1331, author_id: 46},
  {pages: 3, copywright: 1147, author_id: 47},
  {pages: 4, copywright: 808, author_id: 47},
  {pages: 7, copywright: 276, author_id: 48},
  {pages: 2, copywright: 349, author_id: 48},
  {pages: 2, copywright: 1690, author_id: 49},
  {pages: 2, copywright: 1244, author_id: 49},
  {pages: 9, copywright: 1330, author_id: 50},
  {pages: 8, copywright: 464, author_id: 50}
])

PurchasingLocation.create!([
  {name: "Hilll-Prosacco", address: "5871 Schowalter Vista", owner: "Darian Van Grant"},
  {name: "Conroy, Muller and McDermott", address: "9250 Williamson Villages", owner: "Caden Freddie Considine DVM"},
  {name: "Spencer LLC", address: "233 Simonis Square", owner: "Dena Lempi Schimmel Jr."},
  {name: "Feeney-Blanda", address: "945 Williamson Fords", owner: "Kailey Kacey Medhurst IV"},
  {name: "Wilderman-McGlynn", address: "167 Geovanni Mountains", owner: "Destiny Nicolas Block DVM"},
  {name: "Mayert LLC", address: "32784 MacGyver Drive", owner: "Erin Ana Boyer"},
  {name: "Lindgren Inc", address: "771 Jacobson Bridge", owner: "Tyshawn Lorenzo Kshlerin"},
  {name: "Hoeger-Stiedemann", address: "856 Berge Island", owner: "Reggie Florian Willms V"},
  {name: "Luettgen, Wyman and Hegmann", address: "48147 Marquardt Pike", owner: "Archibald Beryl Williamson"},
  {name: "Herman-MacGyver", address: "486 Hegmann Park", owner: "Chyna Alan Glover"},
  {name: "Nicolas Group", address: "2495 Earl Corner", owner: "Nikko Brandon Cormier II"},
  {name: "Anderson-Green", address: "3637 Sipes Rest", owner: "Mr. Kale Sheridan Fay"},
  {name: "Lueilwitz and Sons", address: "607 Parker Shore", owner: "Dean Lia Rempel"},
  {name: "Kozey, Tillman and Haag", address: "98990 Abby Pike", owner: "Yessenia Kirsten Swift"},
  {name: "Kuphal-Turner", address: "25515 Payton Motorway", owner: "Dina Freddy Friesen"},
  {name: "Harber and Sons", address: "35500 Ebert Land", owner: "Mrs. Emma Sidney Kassulke"},
  {name: "Waters-Feil", address: "31423 Ayla Locks", owner: "Erika Eva Runolfsson"},
  {name: "Lueilwitz, Reynolds and Stanton", address: "8521 Franz Ranch", owner: "Ms. Beatrice Hermina Ryan"},
  {name: "Lang Group", address: "447 Schiller Forks", owner: "Aaliyah Gladys Gleichner"},
  {name: "Harvey-Lindgren", address: "166 Marcelo Key", owner: "Miss Eldred Aileen Wolf"},
  {name: "Reynolds Inc", address: "1443 Zion Drive", owner: "Lilyan Reginald Gaylord"},
  {name: "Altenwerth and Sons", address: "6759 Krajcik Fort", owner: "Marielle Creola Ward MD"},
  {name: "Schiller and Sons", address: "31500 Serena Tunnel", owner: "Amparo Rosamond Herman"},
  {name: "Schiller, Balistreri and Ruecker", address: "12744 Mayer Rest", owner: "Mr. Sibyl Brandt Olson"},
  {name: "Monahan-Bartoletti", address: "903 Marian Squares", owner: "Graciela Birdie Rutherford"},
  {name: "DuBuque, Wintheiser and Powlowski", address: "427 Sydney Squares", owner: "Janick Haylie Kshlerin"},
  {name: "Botsford-Pouros", address: "8587 Eichmann Freeway", owner: "Mrs. Nannie Marlene Corwin"},
  {name: "Murray LLC", address: "18551 Gutmann Groves", owner: "Ayden Mafalda Hoppe"},
  {name: "Lebsack Group", address: "460 Gerlach Green", owner: "Miss Hettie Kirsten O'Conner"},
  {name: "Stiedemann Inc", address: "6006 Rafael Crescent", owner: "Lee Edison Schiller"},
  {name: "Gaylord-Rempel", address: "2190 Brooklyn Neck", owner: "Dock Madie Donnelly"},
  {name: "Schulist, Keebler and Zulauf", address: "12214 Spencer Island", owner: "Tanya Lue Boyer"},
  {name: "Pfannerstill, Reinger and Walter", address: "513 Beatty Walks", owner: "Miss Adolfo Waldo Kessler"},
  {name: "Ryan LLC", address: "4997 Herzog Shoals", owner: "Karlee Johnathon Ratke"},
  {name: "Reinger-Sauer", address: "9588 Pink River", owner: "Karli Penelope Bartell"},
  {name: "Bailey, Luettgen and Effertz", address: "410 Jimmy Drive", owner: "Gene Casandra Maggio"},
  {name: "Smith Group", address: "3647 Virginie Port", owner: "Deven Deangelo Anderson I"},
  {name: "Sipes and Sons", address: "4936 Luciano Station", owner: "Mathilde Vicenta Hintz"},
  {name: "Keeling LLC", address: "5664 Edd Turnpike", owner: "Edison Queenie McDermott"},
  {name: "Graham, Mitchell and Dibbert", address: "622 Willms Meadow", owner: "Deshaun Bryana Cartwright"},
  {name: "O'Kon and Sons", address: "9855 Rau Coves", owner: "Westley Waino Parker"},
  {name: "Armstrong-Mitchell", address: "7680 Helen Junction", owner: "Wilhelm Owen Thiel"},
  {name: "Cruickshank, Rempel and McGlynn", address: "6030 Kub Parkway", owner: "Ms. Emmie Nakia Stehr"},
  {name: "Quitzon, MacGyver and Stanton", address: "1816 Garrett Dam", owner: "Christy Dock Medhurst MD"},
  {name: "Sauer-Beier", address: "27606 Edison Ports", owner: "Lafayette Sienna Robel"},
  {name: "Veum, Schimmel and Dooley", address: "70466 Kadin Manors", owner: "Jazlyn Felicita Lebsack"},
  {name: "Sanford-Weimann", address: "39558 Lehner Forks", owner: "Lenny Austyn Bogan I"},
  {name: "Cummerata, Douglas and Herman", address: "2965 Jakob Shores", owner: "Jessica Geovanny Herzog"},
  {name: "Reinger, Witting and Block", address: "572 Stella Forges", owner: "Stone Jeromy Kihn III"},
  {name: "Bosco-Wiza", address: "424 Hoeger Road", owner: "Rosie Melisa Cartwright"}
])

BookPurchasingLocation.create!([
  {book_id: 1, purchasing_location_id: 1},
  {book_id: 2, purchasing_location_id: 1},
  {book_id: 2, purchasing_location_id: 2},
  {book_id: 4, purchasing_location_id: 2},
  {book_id: 3, purchasing_location_id: 3},
  {book_id: 6, purchasing_location_id: 3},
  {book_id: 4, purchasing_location_id: 4},
  {book_id: 8, purchasing_location_id: 4},
  {book_id: 5, purchasing_location_id: 5},
  {book_id: 10, purchasing_location_id: 5},
  {book_id: 6, purchasing_location_id: 6},
  {book_id: 12, purchasing_location_id: 6},
  {book_id: 7, purchasing_location_id: 7},
  {book_id: 14, purchasing_location_id: 7},
  {book_id: 8, purchasing_location_id: 8},
  {book_id: 16, purchasing_location_id: 8},
  {book_id: 9, purchasing_location_id: 9},
  {book_id: 18, purchasing_location_id: 9},
  {book_id: 10, purchasing_location_id: 10},
  {book_id: 20, purchasing_location_id: 10},
  {book_id: 11, purchasing_location_id: 11},
  {book_id: 22, purchasing_location_id: 11},
  {book_id: 12, purchasing_location_id: 12},
  {book_id: 24, purchasing_location_id: 12},
  {book_id: 13, purchasing_location_id: 13},
  {book_id: 26, purchasing_location_id: 13},
  {book_id: 14, purchasing_location_id: 14},
  {book_id: 28, purchasing_location_id: 14},
  {book_id: 15, purchasing_location_id: 15},
  {book_id: 30, purchasing_location_id: 15},
  {book_id: 16, purchasing_location_id: 16},
  {book_id: 32, purchasing_location_id: 16},
  {book_id: 17, purchasing_location_id: 17},
  {book_id: 34, purchasing_location_id: 17},
  {book_id: 18, purchasing_location_id: 18},
  {book_id: 36, purchasing_location_id: 18},
  {book_id: 19, purchasing_location_id: 19},
  {book_id: 38, purchasing_location_id: 19},
  {book_id: 20, purchasing_location_id: 20},
  {book_id: 40, purchasing_location_id: 20},
  {book_id: 21, purchasing_location_id: 21},
  {book_id: 42, purchasing_location_id: 21},
  {book_id: 22, purchasing_location_id: 22},
  {book_id: 44, purchasing_location_id: 22},
  {book_id: 23, purchasing_location_id: 23},
  {book_id: 46, purchasing_location_id: 23},
  {book_id: 24, purchasing_location_id: 24},
  {book_id: 48, purchasing_location_id: 24},
  {book_id: 25, purchasing_location_id: 25},
  {book_id: 50, purchasing_location_id: 25},
  {book_id: 26, purchasing_location_id: 26},
  {book_id: 52, purchasing_location_id: 26},
  {book_id: 27, purchasing_location_id: 27},
  {book_id: 54, purchasing_location_id: 27},
  {book_id: 28, purchasing_location_id: 28},
  {book_id: 56, purchasing_location_id: 28},
  {book_id: 29, purchasing_location_id: 29},
  {book_id: 58, purchasing_location_id: 29},
  {book_id: 30, purchasing_location_id: 30},
  {book_id: 60, purchasing_location_id: 30},
  {book_id: 31, purchasing_location_id: 31},
  {book_id: 62, purchasing_location_id: 31},
  {book_id: 32, purchasing_location_id: 32},
  {book_id: 64, purchasing_location_id: 32},
  {book_id: 33, purchasing_location_id: 33},
  {book_id: 66, purchasing_location_id: 33},
  {book_id: 34, purchasing_location_id: 34},
  {book_id: 68, purchasing_location_id: 34},
  {book_id: 35, purchasing_location_id: 35},
  {book_id: 70, purchasing_location_id: 35},
  {book_id: 36, purchasing_location_id: 36},
  {book_id: 72, purchasing_location_id: 36},
  {book_id: 37, purchasing_location_id: 37},
  {book_id: 74, purchasing_location_id: 37},
  {book_id: 38, purchasing_location_id: 38},
  {book_id: 76, purchasing_location_id: 38},
  {book_id: 39, purchasing_location_id: 39},
  {book_id: 78, purchasing_location_id: 39},
  {book_id: 40, purchasing_location_id: 40},
  {book_id: 80, purchasing_location_id: 40},
  {book_id: 41, purchasing_location_id: 41},
  {book_id: 82, purchasing_location_id: 41},
  {book_id: 42, purchasing_location_id: 42},
  {book_id: 84, purchasing_location_id: 42},
  {book_id: 43, purchasing_location_id: 43},
  {book_id: 86, purchasing_location_id: 43},
  {book_id: 44, purchasing_location_id: 44},
  {book_id: 88, purchasing_location_id: 44},
  {book_id: 45, purchasing_location_id: 45},
  {book_id: 90, purchasing_location_id: 45},
  {book_id: 46, purchasing_location_id: 46},
  {book_id: 92, purchasing_location_id: 46},
  {book_id: 47, purchasing_location_id: 47},
  {book_id: 94, purchasing_location_id: 47},
  {book_id: 48, purchasing_location_id: 48},
  {book_id: 96, purchasing_location_id: 48},
  {book_id: 49, purchasing_location_id: 49},
  {book_id: 98, purchasing_location_id: 49},
  {book_id: 50, purchasing_location_id: 50},
  {book_id: 100, purchasing_location_id: 50}
])


# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# authors
# 50.times do
#   Author.create!(
#     first: Faker::Name.first_name,
#     last: Faker::Name.last_name,
#     age: rand(0..99)
#   )
# end



# # purchasing locations
# 50.times do
#   PurchasingLocation.create!(
#     name: Faker::Company.name,
#     address: Faker::Address.street_address,
#     owner: Faker::Name.name_with_middle
#   )
# end


# authors = Author.all

# authors.each do |author|
#   2.times do
#     Book.create!(
#       pages: rand(10.1000),
#       author_id: author.id,
#       copywright: rand(1800..2016)
#     )
#   end
# end


# purchasing_locations = PurchasingLocation.all

# purchasing_locations.each do |purchasing_location|
#   BookPurchasingLocation.create!(
#     book_id: purchasing_location.id,
#     purchasing_location_id: purchasing_location.id
#   )

#   BookPurchasingLocation.create!(
#     book_id: purchasing_location.id * 2,
#     purchasing_location_id: purchasing_location.id
#   )
# end
